version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.20.0

    steps:
      - checkout

      # Etapa para instalar as dependências e gerar o Storybooks
      - run:
          name: Build Storybook
          command: |
            yarn
            yarn build-storybook

      # # # Etapa para implantar o Storybook no GitHub Pagess
      - run:
          name: Deploy to GitHub Pages
          command: |
            chmod +x ./scripts/deploy.sh
            ./scripts/deploy.sh

workflows:
  deploy-storybook:
    jobs:
      - build:
          filters:
            tags:
              only: /^storybook.*/
            branches:
              ignore: /.*/
      - build:
          filters:
            branches:
              only: master
