version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.20.0

    steps:
      - checkout

      # Etapa para instalar as dependências e gerar o Storybooks
      # - run:
      #     name: Build Storybook
      #     command: |
      #       yarn
      #       yarn build-storybook

      # # # Etapa para implantar o Storybook no GitHub Pagess
      - run:
          name: Deploy to GitHub Pages
          command: |
            git config --global user.email "luizleno15@gmail.com"
            git config --global user.name "luislenosilva15"
            git clone --branch=gh-pages git@github.com:luislenosilva15/circleci-multiple-pages.git gh-pages

            # TARGET_DIR=""

            # if [ -n "$CIRCLE_TAG" ]; then
            #   TARGET_DIR=$(echo "${CIRCLE_TAG}" | sed -E 's/storybook\.//g; s/[.][0-9]+//g')
            # else
            #   TARGET_DIR=$CIRCLE_BRANCH
            # fi

            # echo "Variável ${TARGET_DIR}"
            # mkdir -p gh-pages/pages/$TARGET_DIR
            # cp -R storybook-static/* gh-pages/pages/$TARGET_DIR/

      - run:
          name: Delete non-branch folders
          command: |
            cd gh-pages/pages

            BRANCHES=($(git ls-remote --heads origin | cut -d'/' -f3-))

            # echo "branchs '$(git ls-remote --heads origin)'"

            for branch in "${BRANCHES[@]}"; do
                if [[ "$branch" == *"$dir_name"* ]]; then
                    echo "branch'sim'"
                    break
                fi
            done

            # for directory in */; do
            #   dir_name=${directory%/}
            #   echo "pasta local'$dir_name'"
            #   echo "branch''"

            #   if [[ ! " ${BRANCHES[@]} " =~ " ${dir_name} " ]]; then
            #     sudo rm -rf "$dir_name"
            #     echo "A pasta '$dir_name' foi excluída."
            #   fi
            # done

      # - run:
      #     name: Run Node.js script
      #     command: |
      #       cd gh-pages
      #       node list-folders.js
      #       git add .
      #       git commit -m "Deploy Storybook to GitHub Pages"
      #       git push origin gh-pages

workflows:
  deploy-storybook:
    jobs:
      - build:
          filters:
            tags:
              only: /^storybook.*/
            branches:
              ignore: /.*/
      - build:
          filters:
            branches:
              only: master
