version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest

workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
