version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:20.5-browsers

    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn

workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
